### ISSUE TITLE
No Playback on Arch Linux

### ISSUE THREAD

**Issue by Funnylinkk** [Mrbysco/DiscCord#1]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

NeoForge 21.1.58

### Minecraft version

1.21.1

### Mod version

v1.1.0

### Java version

java 21.0.4

### Issue Description

I cannot get any music to play and am on Arch Linux. I have tried the ytdlp linux executable (both auto downloaded and manually from the latest release) and I am using the 6.1 FFMPEG linux executable. All executables have been chmod +x'ed. When I paste my youtube link and put it into the jukebox, the music downloads successfully but does not play. I am running this as an addition to the Craftoria Modpack.

**Comment by Mrbysco** [comment]
Does the music that's downloaded get converted to .ogg? Because Minecraft can't play other formats.

**Comment by Funnylinkk** [comment]
The two videos I downloaded are stored as WebM and MKV respectively, so no.

**Comment by Mrbysco** [comment]
Then it feels like YoutubeDL is working but FFMpeg is failing to convert

**Comment by Funnylinkk** [comment]
![Screenshot_20240928_184718](https://github.com/user-attachments/assets/aee4b4a5-3a88-49e9-9080-761dd1862ab7)

This is what my config folder looks like. This should work, right?

**Comment by Mrbysco** [comment]
the ffmpeg executable goes in the `ffmpeg` folder so in the end it should be `disccord/ffmpeg/<ffmpeg_executable>`

**Comment by Funnylinkk** [comment]
The files are still being saved as WebM :(

**Comment by Funnylinkk** [comment]
![Screenshot_20240928_190350](https://github.com/user-attachments/assets/eee0df03-9f2c-4fdc-b2de-a7834175a45a)

**Comment by Mrbysco** [comment]
> The files are still being saved as WebM :(. Is there a specific version of FFMPEG to use?

Not really. And I don't have a linux system handy to test

**Comment by Funnylinkk** [comment]
The place where the temp files are stored looks something like this:

/home/user/.local/share/PrismLauncher/instances/Craftoria/minecraft/"/home/user/.local/share/PrismLauncher/instances/

Is it supposed to look like this?

**Comment by Mrbysco** [comment]
The downloaded files should be put in the `/config/disccord/client_downloads` folder

**Comment by Funnylinkk** [comment]
Yes, when they have been converted to ogg, but before that they are put in that folder.

**Comment by Mrbysco** [comment]
No, both the temporary and the converted files should be in there

**Comment by Funnylinkk** [comment]
That's probably what's wrong, then. Any possibility for a fix?

**Comment by Mrbysco** [comment]
For me both the .raw and the .ogg end up in `client_downloads` 
![image](https://github.com/user-attachments/assets/9ac8aa7e-3ffc-4a9b-b5de-7b06d1551213)

**Comment by Mrbysco** [comment]
I'll have to look into it, I wouldn't know where to look since I don't use Linux on my main PC. At best I can test my Ubuntu pc that hasn't been used in a year

**Comment by Funnylinkk** [comment]
That would be fantastic if you could, thanks!
