### ISSUE TITLE
[Bug]: Ffmpeg not converting

### ISSUE THREAD

**Issue by Voshivosh** [Mrbysco/DiscCord#5]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

47.3.11

### Minecraft version

1.20.1

### Mod version

1.1.0

### Java version

17.0.8

### Issue Description

I am running Minecraft on Arch linux. I manually compiled the latest ffmpeg and put it in the expected path, but whenever i go in game and try to play a music disk there are no errors and says it downloads it correctly. I see that the video's are getting download in the client_downloads path but not converting, when i manually convert this to a .ogg file with the same name it is able to play the audio in game. So i assume there is a problem with either the mod failing to find ffmpeg or either run the correct command to convert to .ogg files.

File structure:
disccord
├ client_downloads
│   ├── aedd3f84b1c1a76091ac701c344854bab2552a940abf5bcc218431bcb60ea85c.ogg (manually converted)
│   ├── aedd3f84b1c1a76091ac701c344854bab2552a940abf5bcc218431bcb60ea85c.webm
├ ffmpeg
│   └── ffmpeg
└ youtubedl
 |     └── yt-dlp

**Comment by Mrbysco** [comment]
Hey @Dranoel2 do you have any idea?

**Comment by Dranoel2** [comment]
@Mrbysco Interestingly, I can replicate this with the latest curseforge release but not the source code. If I enable debug output (`-Dforge.logging.console.level=debug`) there's no logging for the ffmpeg command, which would imply the mod isn't even attempting to run it.

`en_us.json` inside the curseforge jar does have my new translations implying that the correct code is in there. I'm quite perplexed with this one; I'll take a closer look at it tomorrow.

**Comment by Mrbysco** [comment]
Same java version both outside and in the dev environment?

**Comment by NevoH72** [comment]
if ya all manage to fix it ya'd been doing god's work.

**Comment by Dranoel2** [comment]
Actually, it seems like this only applies for the 1.20.1 and 1.19.2 versions. @Mrbysco I think it's because #4 was backported to those branches but #3 wasn't?

**Comment by Mrbysco** [comment]
@Dranoel2 I basically copied the files from the main branch to the 1.20 and 1.19 branches and changed the imports where needed

**Comment by Mrbysco** [comment]
Seems like somehow the FFmpeg changes were not brought over when I ported the PR's back...

**Comment by Mrbysco** [comment]
Could you try with https://legacy.curseforge.com/minecraft/mc-mods/disccord/files/5912191 ?
