### ISSUE TITLE
[Suggestion]: Backport to 1.20.1

### ISSUE THREAD

**Issue by allogic** [Mrbysco/DiscCord#6]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Greetings,

is there a way to backport to 1.20.1
the sophisticated backpack changes are really nice!

BR
0x616c

**Comment by Mrbysco** [comment]
There is already a 1.20 version of the mod, it just doesn't have the Sophisticated support

**Comment by allogic** [comment]
That' why I'm asking.. I do lot's of C.
i can't merge these changes :/
